logging:
    file: ${LOG_TEMP:./logs}/${spring.application.name}.log
    level:
        cn.com.xgit: debug
management:
    endpoints:
        web:
            exposure:
                include: bus-refresh,health,info
server:
    port: 9000
spring:
    cloud:
        bus:
            enabled: true
            trace:
                enabled: true
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        password: ''
        url: jdbc:mysql://127.0.0.1:3306/parts_rm?characterEncoding=UTF-8
        username: root
    rabbitmq:
        host: 10.100.2.109
        password: admin
        port: 5672
        username: admin
    session:
        store-type: none
xgxx:
    customs:
        claimKeyCreated: xgxxDev
        claimKeySecret: oooooo33333
        destinationUrl: /ius/auth/login
        jwtExpiration: 1200
        loginOutUrls: /ius/auth/logout
        loginUrls: /ius/auth/login,/ius/auth/sigin
        signInPage: /ius/auth/login
        signOutPage: /ius/auth/logout
        signOutSuccessUrl: /ius/auth/login
        
#        redirectErrorPage403: http://10.100.2.109:9101/web/index
#        redirectErrorPage404: http://10.100.2.109:9101/web/index
#        redirectErrorPage500: http://10.100.2.109:9101/web/index
    social:
        github:
            appId: c2414a22b635afbfb5ec
            appSecret: e17c54e4d78ab22fc1a335a3eb796a2074598a8e
            callback: http://127.0.0.1:9000/connet/github
zuul:
    host:
        connect-timeout-millis: 600000
        socket-timeout-millis: 600000
    max:
        host:
            connections: 500
    routes:
        api-a:
            path: /ius/**
            serviceid: parts-auth-server
        api-b:
            path: /cos/**
            serviceid: copper-server
