server:
  port: 9000
spring:
  session:
    store-type: none

zuul:
  routes:
    main-data:
      path: /api/main-data/**
      serviceId: demo1
    api-a:
      path: /cop/**
      serviceid: copper-purchase
    api-b:
      path: /cos/**
      serviceid: copper-server
    api-c:
      path: /web/**
      serviceid: copper-surface
    api-d:
      path: /ius-d/**
      serviceId: fast-auth-server
    api-e:
      path: /ss/**
      serviceId: storage-server
    api-f:
      path: /ss-cdw/**
      serviceId: storage-server-cdw
    api-g:
      path: /ius-s/**
      serviceId: storage-server-v
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 600000
    connect-timeout-millis: 600000

xgxx:
  customs:
    destinationUrl: /ius/auth/login
    signInPage: /ius/auth/login
    signOutPage: /logout
    signOutSuccessUrl: /ius/auth/login
    claimKeyCreated: xgxxDev
    jwtExpiration: 1200

logging:
  file: ${LOG_TEMP:./logs}/${spring.application.name}.log
  level:
    cn.com.xgit: debug
