server:
  port: 9000
spring:
  session:
    store-type: none

zuul:
  routes:
    api-a:
      path: /ius/**
      serviceid: parts-auth-server
    api-b:
      path: /cos/**
      serviceid: copper-server
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 600000
    connect-timeout-millis: 600000

xgxx:
  customs:
    destinationUrl: /ius/auth/login
    signInPage: /ius/auth/login
    signOutPage: /ius/auth/logout
    signOutSuccessUrl: /ius/auth/login
    loginUrls: /ius/auth/login,/ius/auth/sigin
    loginOutUrls: /ius/auth/logout

    claimKeySecret: oooooo
    claimKeyCreated: xgxxDev
    jwtExpiration: 1200
#    redirectErrorPage403: http://10.100.2.109:9101/web/index
    redirectErrorPage404: http://10.100.2.109:9101/web/index
#    redirectErrorPage500: http://10.100.2.109:9101/web/index
logging:
  file: ${LOG_TEMP:./logs}/${spring.application.name}.log
  level:
    cn.com.xgit: debug
